variables:
    'DJANGO_SETTINGS_MODULE': rndgui.settings
stages:
    - test
    - deploy
nose_test:
    stage: test
    script:
        - bash test/init.sh
    tags:
        - rnd
    except:
        - master
deploy_dev:
    environment: production
    stage: deploy
    script:
        - fab dev deploy
        - curl http://sv2.bpc.in:8000
    only:
        - develop
    tags:
        - rnd

deploy_production:
    environment: production
    stage: deploy
    script:
        - fab production1 deploy
        - curl http://sv2-web.bt.bpc.in
    only:
        - master
    tags:
        - rnd
