stages:
    - test
    - deploy
nose_test:
    stage: test
    script:
        - bash test/init.sh
    tags:
        - rnd
    except:
        - master
deploy to production:
    environment: production
    stage: deploy
    script:
        - fab production1 deploy
        - curl http://sv2-web.bt.bpc.in
    only:
        - master
    tags:
        - rnd
